### ISSUE TITLE
生成工程失败

### ISSUE THREAD

**Issue by wray007** [netease-youdao/hex#109]
Updating projects from gyp files...
gyp: name 'v8_postmortem_support' is not defined while evaluating condition 'v8_postmortem_support=="true"' in ..\third_
party\node\node.gyp while loading dependencies of ..\third_party\WebKit\Source\core\core.gyp while loading dependencies
of ..\third_party\WebKit\Source\web\web.gyp while loading dependencies of ..\third_party\WebKit\public\blink.gyp while l
oading dependencies of ..\ppapi\ppapi_internal.gyp while loading dependencies of ..\content\content.gyp while loading de
pendencies of ..\components\components.gyp while loading dependencies of ..\cef\cef.gyp while loading dependencies of he
x.gyp while trying to load hex.gyp
Traceback (most recent call last):
  File "tools\gclient_hook.py", line 69, in <module>
    RunAction(hex_dir, gyper)
  File "E:\chromium\220934\src\hex\tools\gclient_util.py", line 39, in RunAction
    command, cwd=dir, always=True)
  File "D:\depot_tools\gclient_utils.py", line 220, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "D:\depot_tools\gclient_utils.py", line 397, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
subprocess2.CalledProcessError: Command E:\chromium\220934\src\third_party\python_26\python.exe tools/gyp_hex hex.gyp -I
 hex.gypi returned non-zero exit status 1 in E:\chromium\220934\src\hex

E:\chromium\220934\src\hex>

**Comment by 0x0000000000000000000000000** [comment]
你把源码连同chromiun发打包网盘给我，我帮你看看。

**Comment by wray007** [comment]
已经上传到网盘上了，下载地址：http://pan.baidu.com/s/1hq3SNLq

谢谢！

**Comment by slikel** [comment]
我编译的时候也出现了这种问题，有些变量未定义

**Comment by wray007** [comment]
你的解决了吗

**Comment by slikel** [comment]
还没有，今天去网盘下载你上传的代码了，编译的时候出现有未定义的变量···出问题的地方是调用chromium源码中的src/tools/version.gyp报出来的，有个os_POSIX未定义，我在想是不是chromium源码版本的问题，明天再试试看
我的环境是：win8.1 x64，vs2013
